//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.21 at 01:33:23 AM PDT 
//


package org.smarterbalanced.irv.metadata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="smarterAppMetadata"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="SmarterAppItemDescriptor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="InteractionType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                   &lt;element name="SecurityStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="MinimumGrade" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="IntendedGrade" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="MaximumGrade" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="BrailleType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="AllowCalculator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="MathematicalPractice" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="AssociatedTutorial" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="AssociatedWordlist" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="StandardPublication" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Publication" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="PrimaryStandard" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="SecondaryStandard" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="MaximumNumberOfPoints" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="ScorePoints" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ItemSpecFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="StimulusFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="EducationalDifficulty" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DepthOfKnowledge" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="AdministrationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="IrtDimension" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="IrtDimensionPurpose" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IrtModelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IrtStatDomain" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IrtScore" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="IrtWeight" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="IrtParameter" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OtherMetadata1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OtherMetadata2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smarterAppMetadata",
    "otherMetadata1",
    "otherMetadata2"
})
@XmlRootElement(name = "metadata")
public class Metadata {

    @XmlElement(required = true)
    protected Metadata.SmarterAppMetadata smarterAppMetadata;
    @XmlElement(name = "OtherMetadata1", required = true)
    protected String otherMetadata1;
    @XmlElement(name = "OtherMetadata2", required = true)
    protected String otherMetadata2;

    /**
     * Gets the value of the smarterAppMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata.SmarterAppMetadata }
     *     
     */
    public Metadata.SmarterAppMetadata getSmarterAppMetadata() {
        return smarterAppMetadata;
    }

    /**
     * Sets the value of the smarterAppMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata.SmarterAppMetadata }
     *     
     */
    public void setSmarterAppMetadata(Metadata.SmarterAppMetadata value) {
        this.smarterAppMetadata = value;
    }

    /**
     * Gets the value of the otherMetadata1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherMetadata1() {
        return otherMetadata1;
    }

    /**
     * Sets the value of the otherMetadata1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherMetadata1(String value) {
        this.otherMetadata1 = value;
    }

    /**
     * Gets the value of the otherMetadata2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherMetadata2() {
        return otherMetadata2;
    }

    /**
     * Sets the value of the otherMetadata2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherMetadata2(String value) {
        this.otherMetadata2 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="SmarterAppItemDescriptor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="InteractionType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *         &lt;element name="SecurityStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="MinimumGrade" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="IntendedGrade" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="MaximumGrade" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="BrailleType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="AllowCalculator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="MathematicalPractice" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="AssociatedTutorial" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="AssociatedWordlist" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="StandardPublication" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Publication" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="PrimaryStandard" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="SecondaryStandard" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="MaximumNumberOfPoints" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="ScorePoints" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ItemSpecFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="StimulusFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="EducationalDifficulty" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DepthOfKnowledge" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="AdministrationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="IrtDimension" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="IrtDimensionPurpose" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IrtModelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IrtStatDomain" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IrtScore" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="IrtWeight" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="IrtParameter" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifier",
        "itemAuthorIdentifier",
        "smarterAppItemDescriptor",
        "interactionType",
        "version",
        "subject",
        "language",
        "securityStatus",
        "minimumGrade",
        "intendedGrade",
        "maximumGrade",
        "brailleType",
        "allowCalculator",
        "mathematicalPractice",
        "associatedTutorial",
        "associatedWordlist",
        "standardPublication",
        "maximumNumberOfPoints",
        "scorePoints",
        "itemSpecFormat",
        "stimulusFormat",
        "educationalDifficulty",
        "depthOfKnowledge",
        "administrationDate",
        "irtDimension"
    })
    public static class SmarterAppMetadata {

        @XmlElement(name = "Identifier")
        protected int identifier;
        @XmlElement(name = "itemAuthorIdentifier")
    	protected String itemAuthorIdentifier;
        @XmlElement(name = "SmarterAppItemDescriptor", required = true)
        protected String smarterAppItemDescriptor;
        @XmlElement(name = "InteractionType", required = true)
        protected String interactionType;
        @XmlElement(name = "Version")
        protected int version;
        @XmlElement(name = "Subject", required = true)
        protected String subject;
        @XmlElement(name = "Language", required = true)
        protected List<String> language;
        @XmlElement(name = "SecurityStatus", required = true)
        protected String securityStatus;
        @XmlElement(name = "MinimumGrade")
        protected int minimumGrade;
        @XmlElement(name = "IntendedGrade")
        protected int intendedGrade;
        @XmlElement(name = "MaximumGrade")
        protected int maximumGrade;
        @XmlElement(name = "BrailleType", required = true)
        protected String brailleType;
        @XmlElement(name = "AllowCalculator", required = true)
        protected String allowCalculator;
        @XmlElement(name = "MathematicalPractice")
        protected int mathematicalPractice;
        @XmlElement(name = "AssociatedTutorial")
        protected int associatedTutorial;
        @XmlElement(name = "AssociatedWordlist")
        protected int associatedWordlist;
        @XmlElement(name = "StandardPublication", required = true)
        protected List<Metadata.SmarterAppMetadata.StandardPublication> standardPublication;
        @XmlElement(name = "MaximumNumberOfPoints")
        protected int maximumNumberOfPoints;
        @XmlElement(name = "ScorePoints", required = true)
        protected String scorePoints;
        @XmlElement(name = "ItemSpecFormat", required = true)
        protected String itemSpecFormat;
        @XmlElement(name = "StimulusFormat", required = true)
        protected String stimulusFormat;
        @XmlElement(name = "EducationalDifficulty", required = true)
        protected String educationalDifficulty;
        @XmlElement(name = "DepthOfKnowledge")
        protected int depthOfKnowledge;
        @XmlElement(name = "AdministrationDate", required = true)
        protected String administrationDate;
        @XmlElement(name = "IrtDimension", required = true)
        protected List<Metadata.SmarterAppMetadata.IrtDimension> irtDimension;

        /**
         * Gets the value of the identifier property.
         * 
         */
        public int getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         */
        public void setIdentifier(int value) {
            this.identifier = value;
        }
        
    	public String getItemAuthorIdentifier() {
    		return itemAuthorIdentifier;
    	}

    	public void setItemAuthorIdentifier(String itemAuthorIdentifier) {
    		this.itemAuthorIdentifier = itemAuthorIdentifier;
    	}


        /**
         * Gets the value of the smarterAppItemDescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSmarterAppItemDescriptor() {
            return smarterAppItemDescriptor;
        }

        /**
         * Sets the value of the smarterAppItemDescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSmarterAppItemDescriptor(String value) {
            this.smarterAppItemDescriptor = value;
        }

        /**
         * Gets the value of the interactionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInteractionType() {
            return interactionType;
        }

        /**
         * Sets the value of the interactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInteractionType(String value) {
            this.interactionType = value;
        }

        /**
         * Gets the value of the version property.
         * 
         */
        public int getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         */
        public void setVersion(int value) {
            this.version = value;
        }

        /**
         * Gets the value of the subject property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubject() {
            return subject;
        }

        /**
         * Sets the value of the subject property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubject(String value) {
            this.subject = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLanguage() {
            if (language == null) {
                language = new ArrayList<String>();
            }
            return this.language;
        }

        /**
         * Gets the value of the securityStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecurityStatus() {
            return securityStatus;
        }

        /**
         * Sets the value of the securityStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecurityStatus(String value) {
            this.securityStatus = value;
        }

        /**
         * Gets the value of the minimumGrade property.
         * 
         */
        public int getMinimumGrade() {
            return minimumGrade;
        }

        /**
         * Sets the value of the minimumGrade property.
         * 
         */
        public void setMinimumGrade(int value) {
            this.minimumGrade = value;
        }

        /**
         * Gets the value of the intendedGrade property.
         * 
         */
        public int getIntendedGrade() {
            return intendedGrade;
        }

        /**
         * Sets the value of the intendedGrade property.
         * 
         */
        public void setIntendedGrade(int value) {
            this.intendedGrade = value;
        }

        /**
         * Gets the value of the maximumGrade property.
         * 
         */
        public int getMaximumGrade() {
            return maximumGrade;
        }

        /**
         * Sets the value of the maximumGrade property.
         * 
         */
        public void setMaximumGrade(int value) {
            this.maximumGrade = value;
        }

        /**
         * Gets the value of the brailleType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrailleType() {
            return brailleType;
        }

        /**
         * Sets the value of the brailleType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrailleType(String value) {
            this.brailleType = value;
        }

        /**
         * Gets the value of the allowCalculator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowCalculator() {
            return allowCalculator;
        }

        /**
         * Sets the value of the allowCalculator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowCalculator(String value) {
            this.allowCalculator = value;
        }

        /**
         * Gets the value of the mathematicalPractice property.
         * 
         */
        public int getMathematicalPractice() {
            return mathematicalPractice;
        }

        /**
         * Sets the value of the mathematicalPractice property.
         * 
         */
        public void setMathematicalPractice(int value) {
            this.mathematicalPractice = value;
        }

        /**
         * Gets the value of the associatedTutorial property.
         * 
         */
        public int getAssociatedTutorial() {
            return associatedTutorial;
        }

        /**
         * Sets the value of the associatedTutorial property.
         * 
         */
        public void setAssociatedTutorial(int value) {
            this.associatedTutorial = value;
        }

        /**
         * Gets the value of the associatedWordlist property.
         * 
         */
        public int getAssociatedWordlist() {
            return associatedWordlist;
        }

        /**
         * Sets the value of the associatedWordlist property.
         * 
         */
        public void setAssociatedWordlist(int value) {
            this.associatedWordlist = value;
        }

        /**
         * Gets the value of the standardPublication property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the standardPublication property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStandardPublication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Metadata.SmarterAppMetadata.StandardPublication }
         * 
         * 
         */
        public List<Metadata.SmarterAppMetadata.StandardPublication> getStandardPublication() {
            if (standardPublication == null) {
                standardPublication = new ArrayList<Metadata.SmarterAppMetadata.StandardPublication>();
            }
            return this.standardPublication;
        }

        /**
         * Gets the value of the maximumNumberOfPoints property.
         * 
         */
        public int getMaximumNumberOfPoints() {
            return maximumNumberOfPoints;
        }

        /**
         * Sets the value of the maximumNumberOfPoints property.
         * 
         */
        public void setMaximumNumberOfPoints(int value) {
            this.maximumNumberOfPoints = value;
        }

        /**
         * Gets the value of the scorePoints property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScorePoints() {
            return scorePoints;
        }

        /**
         * Sets the value of the scorePoints property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScorePoints(String value) {
            this.scorePoints = value;
        }

        /**
         * Gets the value of the itemSpecFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemSpecFormat() {
            return itemSpecFormat;
        }

        /**
         * Sets the value of the itemSpecFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemSpecFormat(String value) {
            this.itemSpecFormat = value;
        }

        /**
         * Gets the value of the stimulusFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStimulusFormat() {
            return stimulusFormat;
        }

        /**
         * Sets the value of the stimulusFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStimulusFormat(String value) {
            this.stimulusFormat = value;
        }

        /**
         * Gets the value of the educationalDifficulty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEducationalDifficulty() {
            return educationalDifficulty;
        }

        /**
         * Sets the value of the educationalDifficulty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEducationalDifficulty(String value) {
            this.educationalDifficulty = value;
        }

        /**
         * Gets the value of the depthOfKnowledge property.
         * 
         */
        public int getDepthOfKnowledge() {
            return depthOfKnowledge;
        }

        /**
         * Sets the value of the depthOfKnowledge property.
         * 
         */
        public void setDepthOfKnowledge(int value) {
            this.depthOfKnowledge = value;
        }

        /**
         * Gets the value of the administrationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdministrationDate() {
            return administrationDate;
        }

        /**
         * Sets the value of the administrationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdministrationDate(String value) {
            this.administrationDate = value;
        }

        /**
         * Gets the value of the irtDimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the irtDimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIrtDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Metadata.SmarterAppMetadata.IrtDimension }
         * 
         * 
         */
        public List<Metadata.SmarterAppMetadata.IrtDimension> getIrtDimension() {
            if (irtDimension == null) {
                irtDimension = new ArrayList<Metadata.SmarterAppMetadata.IrtDimension>();
            }
            return this.irtDimension;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="IrtDimensionPurpose" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IrtModelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IrtStatDomain" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IrtScore" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="IrtWeight" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="IrtParameter" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "irtDimensionPurpose",
            "irtModelType",
            "irtStatDomain",
            "irtScore",
            "irtWeight",
            "irtParameter"
        })
        public static class IrtDimension {

            @XmlElement(name = "IrtDimensionPurpose", required = true)
            protected String irtDimensionPurpose;
            @XmlElement(name = "IrtModelType", required = true)
            protected String irtModelType;
            @XmlElement(name = "IrtStatDomain", required = true)
            protected String irtStatDomain;
            @XmlElement(name = "IrtScore")
            protected int irtScore;
            @XmlElement(name = "IrtWeight")
            protected int irtWeight;
            @XmlElement(name = "IrtParameter", required = true)
            protected List<Metadata.SmarterAppMetadata.IrtDimension.IrtParameter> irtParameter;

            /**
             * Gets the value of the irtDimensionPurpose property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIrtDimensionPurpose() {
                return irtDimensionPurpose;
            }

            /**
             * Sets the value of the irtDimensionPurpose property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIrtDimensionPurpose(String value) {
                this.irtDimensionPurpose = value;
            }

            /**
             * Gets the value of the irtModelType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIrtModelType() {
                return irtModelType;
            }

            /**
             * Sets the value of the irtModelType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIrtModelType(String value) {
                this.irtModelType = value;
            }

            /**
             * Gets the value of the irtStatDomain property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIrtStatDomain() {
                return irtStatDomain;
            }

            /**
             * Sets the value of the irtStatDomain property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIrtStatDomain(String value) {
                this.irtStatDomain = value;
            }

            /**
             * Gets the value of the irtScore property.
             * 
             */
            public int getIrtScore() {
                return irtScore;
            }

            /**
             * Sets the value of the irtScore property.
             * 
             */
            public void setIrtScore(int value) {
                this.irtScore = value;
            }

            /**
             * Gets the value of the irtWeight property.
             * 
             */
            public int getIrtWeight() {
                return irtWeight;
            }

            /**
             * Sets the value of the irtWeight property.
             * 
             */
            public void setIrtWeight(int value) {
                this.irtWeight = value;
            }

            /**
             * Gets the value of the irtParameter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the irtParameter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIrtParameter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Metadata.SmarterAppMetadata.IrtDimension.IrtParameter }
             * 
             * 
             */
            public List<Metadata.SmarterAppMetadata.IrtDimension.IrtParameter> getIrtParameter() {
                if (irtParameter == null) {
                    irtParameter = new ArrayList<Metadata.SmarterAppMetadata.IrtDimension.IrtParameter>();
                }
                return this.irtParameter;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "value"
            })
            public static class IrtParameter {

                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "Value")
                protected int value;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public int getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(int value) {
                    this.value = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Publication" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="PrimaryStandard" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="SecondaryStandard" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "publication",
            "primaryStandard",
            "secondaryStandard"
        })
        public static class StandardPublication {

            @XmlElement(name = "Publication", required = true)
            protected String publication;
            @XmlElement(name = "PrimaryStandard", required = true)
            protected String primaryStandard;
            @XmlElement(name = "SecondaryStandard", required = true)
            protected List<String> secondaryStandard;

            /**
             * Gets the value of the publication property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPublication() {
                return publication;
            }

            /**
             * Sets the value of the publication property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPublication(String value) {
                this.publication = value;
            }

            /**
             * Gets the value of the primaryStandard property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrimaryStandard() {
                return primaryStandard;
            }

            /**
             * Sets the value of the primaryStandard property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrimaryStandard(String value) {
                this.primaryStandard = value;
            }

            /**
             * Gets the value of the secondaryStandard property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the secondaryStandard property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSecondaryStandard().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getSecondaryStandard() {
                if (secondaryStandard == null) {
                    secondaryStandard = new ArrayList<String>();
                }
                return this.secondaryStandard;
            }

        }

    }

}
